openclimatefix/ocf-data-sampler

ocf_data_sampler/select/fill_time_periods.py
Small refactor of `fill_time_periods` to remove using `iterrows()` to hopefully make it more efficient 
A unit test already existed for this which is great so just checked that still passes
=> Refactor fill time periods function

ocf_data_sampler/torch_datasets/pvnet_uk_regional.py, tests/torch_datasets/test_pvnet_uk_regional.py
Allows the sampler to not use GSP data if the gsp_zarr_path is `None` or `""`
Should make GSP mocking in openclimatefix/uk-pvnet-app#118 unnecessary
=> Allow GSP data to be optional

ocf_data_sampler/load/gsp.py, ocf_data_sampler/load/nwp/providers/ecmwf.py, ocf_data_sampler/load/nwp/providers/ukv.py, ocf_data_sampler/load/satellite.py, ocf_data_sampler/load/utils.py, ocf_data_sampler/select/dropout.py, ocf_data_sampler/select/select_time_slice.py, tests/select/test_dropout.py
All data sources are currently loaded as `xr.DataArray`, so stripped out `xr.Dataset` hints where appropriate (basically everywhere except for functions called inside loaders that do operate on a ds)
Ran built-in tests
=> strip out xr.Dataset type hints

ocf_data_sampler/numpy_batch/__init__.py, ocf_data_sampler/numpy_batch/gsp.py, ocf_data_sampler/numpy_batch/nwp.py, ocf_data_sampler/numpy_batch/satellite.py, ocf_data_sampler/torch_datasets/pvnet_uk_regional.py, tests/numpy_batch/test_gsp.py, tests/numpy_batch/test_nwp.py, tests/numpy_batch/test_satellite.py, tests/numpy_batch/test_sun_position.py, tests/torch_datasets/test_pvnet_uk_regional.py
- Add imports from numpy_batch instead of numpy_batch.[source]
- remove prefixes from batchkeys
_Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.
Please also list any relevant details for your test configuration_
=> rm prefixes and add cleaner imports fo batchkeys

README.md
Updated the broken link to reference the correct torch datasets documentation
This PR resolves an issue in the torch datasets documentation where the existing link was not working as expected. The broken link has been updated to reference the correct file in the repository.
**Changes Made:**
Replaced the broken link with the correct link:
https://github.com/openclimatefix/ocf-data-sampler/blob/07f412cd125a154c527444a5ff7bd0ba4ede4d30/ocf_data_sampler/torch_datasets/README.md?plain=1#L4
**Why This Change Was Made:**
The previous link in the documentation was non-functional, making it difficult for users to access relevant details about the torch datasets.
This change ensures that users are directed to the correct location for further information.
**How to Verify:**
Click on the updated …
=> Fix broken link in torch datasets documentation

ocf_data_sampler/sample/base.py, scripts/refactor_site.py, tests/test_sample/test_base.py
#168 
_Added the `copy_batch_to_device` function along with tests._
=> copy_batch_to_device functionality

MANIFEST.in
Removes manifest file. [This line](https://github.com/openclimatefix/ocf-data-sampler/blob/3054a5721ba2897ec76841bba97ac4c7d0e34d2c/pyproject.toml#L59) in pyproject.toml supercedes it, specifying to setuptools to include CSV files in the package.
=> chore(root): Remove uneeded MANIFEST file

ocf_data_sampler/select/select_time_slice.py, ocf_data_sampler/torch_datasets/utils/valid_time_periods.py
Recently in one of the mob programming sessions we [updated the config model ](https://github.com/openclimatefix/ocf-data-sampler/pull/183/files#diff-7d8af53f8ccb0fe5ee493bd54771546ce767703b9d7ea18f09d70e1041563ae2) to update the null value of `dropout_timedeltas_minutes` from `None` to an empty list. This has broken some downstream code which still expects the null value of the list to be `None`.
This PR allows the functions where `dropout_timedeltas_minutes` is passed in to run with an empty list
=> Downstream update for `dropout_timedeltas_minutes` in config changing from `None`-> `[]` for null value

ocf_data_sampler/load/utils.py
This PR is a proposal to fix issue #211. See the issue for full details
Fixes #
I have run this locally to create samples which are converted straight to torch tensors without being saved first
I have made sure the samples created by the UK PVNet sampler all the numpy arrays in the numpy batch have positive strides
Also this is a minimal example showing that the fix works:
```
import xarray as xr
import numpy as np
import dask
x_coords = np.arange(9, -1, -1)
# The underlying data is lazy - values [9,8,7,...,1,0]
values = dask.array.arange(9, -1, -1)
da = xr.DataArray(values, dims=['x'], coords={'x': x_coords}, name='example_data')
da = da.isel(x=slice(None, None, -1))
print("x-strides", da.x.data.strides)  # >> x-strides (-8,)
print("data-stride", da.values.strides)  # >> data-stride (8,) …
```
=> Make coords contiguous if reversed in loading

ocf_data_sampler/load/nwp/providers/utils.py
We are currently getting this warning when opening NWP datasets. The NWP datasets have a `step` dimension which is a timedelta wrt t0. 
```
FutureWarning: In a future version of xarray decode_timedelta will default to False rather than None. 
To silence this warning, set decode_timedelta to True, False, or a 'CFTimedeltaCoder' instance.
```
This PR fixes this warning
=> Set param for incoming deprecation

ocf_data_sampler/select/dropout.py, tests/select/test_dropout.py
The current dropout functionality was patched in a recent PR #183, this changed how the dropout_time was set when no dropout was specified in the configuration to return t0, instead of None. This introduced NaNs in times after t0 which isn't the intended outcome.
This has been fixed by reinstating the previous functionality, setting dropout_time to None where dropout is not desired, with ds being returned in the apply_dropout function if the dropout_time is None.
The existing test, `test_draw_dropout_time_none` has also been updated to reflect the None case.
_If your changes affect data processing, have you plotted any changes? i.e. have you done a quick sanity check?_
I have inspected and printed the generation locally to track and verify the changes.
=> patch dropout function for no dropout case

ocf_data_sampler/select/select_spatial_slice.py, pyproject.toml, tests/select/test_select_spatial_slice.py
Main refactor aspects are as follows:
CoordinateConverter Class - introduced to encapsulate coordinate transformations.
Combined Pixel Index Function - two pixel-index functions merged into one, using the CoordinateConverter class to handle different coordinate systems.
Improved Padding Logic - pre-existing padding logic simplified by calculating quantities explicitly.
New test added to cover cases with allow_partial_slice=False (not sure if truly necessary).
=> Spatial slice select update

ocf_data_sampler/select/find_contiguous_time_periods.py, tests/select/test_find_contiguous_time_periods.py
Updates `intersection_of_2_dataframes_of_periods()` for the edge cases in the TODO section
i.e. intersections like these now have the expected overlaps
```
a: |----|
b:      |---|
>>      |
a:   |
b:   |---|
>>   |
```
Also added tests for these cases (and other untested cases) and added a utility function to the test module to simplify some out our testing code for this module
This partly solves (though not fully) #192
=> Allow periods which start and end at the same timestamp

ocf_data_sampler/config/model.py, ocf_data_sampler/torch_datasets/sample/uk_regional.py, ocf_data_sampler/torch_datasets/utils/validation_utils.py, tests/test_data/configs/pvnet_test_config.yaml, tests/torch_datasets/sample/test_uk_regional_sample.py, tests/torch_datasets/test_site.py
Alongside updating related tests, two new functions:
validate_sample (inside UKRegionalSample class): Checks if individual sample meets criteria by verifying required keys exist, data shapes match expected dimensions and validating structure for NWP.
validate_samples: Processes multiple UKRegionalSample objects - applies validation to each using provided configuration.
Related to: https://github.com/openclimatefix/ocf-data-sampler/issues/227
=> Validate samples after load

ocf_data_sampler/config/model.py, ocf_data_sampler/load/gsp.py, ocf_data_sampler/load/load_dataset.py, ocf_data_sampler/torch_datasets/datasets/pvnet_uk.py, scripts/download_gsp_location_data.py, tests/load/test_load_gsp.py
Part of openclimatefix/uk-pvnet-app#289
This adds the option to use the new GSP boundaries when loading the GSP data. The current default is to use the old boundaries to maintain backwards compatibility.
I have added a new script which creates the new GSP locations so the data is traceable - this solves #10
=> Add new GSP boundaries as option

ocf_data_sampler/load/nwp/providers/gfs.py
Small changes to make gfs more flexible
This makes renaming from "init_time" to "init_time_utc" optional
Helps with #251 
```
from ocf_data_sampler.load.nwp.providers.gfs import open_gfs
open_gfs('s3://ocf-open-data-pvnet/data/gfs/v4/2023.zarr')
```
=> gfs changes for open-data-pvnet

ocf_data_sampler/torch_datasets/datasets/pvnet_uk.py
Currently in the UK regional dataset we have an attribute `index_pairs` which is an array of all of the possible (t0_index, location_index) pairs. This can be a very large array when training on a few years of data. I created a version of the dataset from 2019-2022 and this this array was 300MB! When we wrap the dataset in a pytorch DataLoader and use multiple workers this creates a copy of this index array in each worker. So for a typical 32 workers this can be 10GB of index pairs
Storing this index array was a design pattern copied across from `ocf_datapipes` and we actually don't need it here.
This PR removes the `index_pairs` array and calculates the values the values that would be in each index of `index_pairs` on the fly
=> remove stored index pairs

ocf_data_sampler/select/select_spatial_slice.py, tests/select/test_select_spatial_slice.py
I try to improved the ValueError message when padding is required by including detailed index variables  like (left_idx, right_idx). This helps users understand why padding is needed.
Fixes #266
- Tested using pytest.
**Proof of Test**
>![Screenshot from 2025-05-29 14-38-57](https://github.com/user-attachments/assets/81feb256-3cd5-4880-89e6-9ca21cfa2d61)
_If your changes affect data processing, have you plotted any changes? i.e. have you done a quick sanity check?_
=> Improved Error Message

tests/conftest.py, tests/load/test_load_sites.py, tests/test_data/configs/site_test_config.yaml, tests/torch_datasets/test_site.py
- site_test_config.yaml for site only tests.
- site_test_config_path and default_data_site_model fixtures, and refactored site_config_filename fixture to load new config.
- Modified shapes and lengths in tests/torch_datasets/test_site.py for site data and adjusted manual data generation within test_process_and_combine_site_sample_dict.
- Modified site_config_filename fixture to set SolarPosition intervals to match time window of site data sample.
=> Dedicated site only config for testing

ocf_data_sampler/config/model.py, tests/config/test_config.py, tests/test_data/configs/test_config.yaml
This PR adds validation to ensure `accum_channels` specified in the NWP configuration are a subset of the configured `channels`. This prevents runtime errors when attempting to compute differences for channels not present in the data.
Key changes:
- Added Pydantic validator to check `accum_channels ⊂ channels`
- Added required normalization constant checks for diff_ prefixed channels
- Added comprehensive unit tests for both valid and invalid cases
Fixes #236
Added 2 new test cases in `tests/config/test_config.py`:
1. `test_valid_accum_channels`: Verifies valid configuration with:
- accum_channels subset of channels
- Proper diff_ normalization constants
2. `test_invalid_accum_channels`: Checks proper ValueError is raised when:
- accum_channels contains non-existent channel
- Error …
=> Validate channels

ocf_data_sampler/load/nwp/nwp.py
Often the UKV coords are stored as ints. This changes the validation check to allow for this
=> Fix  UKV coord check

ocf_data_sampler/numpy_sample/__init__.py, ocf_data_sampler/numpy_sample/datetime_features.py, ocf_data_sampler/numpy_sample/site.py, ocf_data_sampler/torch_datasets/datasets/site.py, tests/numpy_sample/test_datetime_features.py, tests/torch_datasets/test_site.py
Solves #159 
Removes the source prefix from the datetime encodings. This will require an update in PVNet as well - so this should be a minor bump
=> Remove time feature prefix

ocf_data_sampler/load/open_xarray_tensorstore.py
Change the way we merge attrs. The previous one was a little too strict as some of the non-important attrs in our different satellite datasets don't match. E.g. there is an attr which corresponds to the valid time, and is different for all of the sat datasets. We don't use these attrs
=> More lenient attr merging

ocf_data_sampler/torch_datasets/datasets/pvnet_uk.py, ocf_data_sampler/torch_datasets/datasets/site.py, ocf_data_sampler/utils.py, tests/torch_datasets/test_pvnet_uk.py
This PR adds async reading of tensorstore arrays. Previously we were loading the data from each of the input datasets sequentially. Using xarray-tensorstore we can load them simultaneously, and this is the [recommendation in xarray-tensorstore itself](https://github.com/google/xarray-tensorstore?tab=readme-ov-file#usage). 
In some local tests I did on donatello, using ECMWF, UKV, satellite and cloudcasting inputs (i.e. a lot of inputs) this sped up the time to create a PVNet UK regional sample by around 20% in my case.
=> Add async reading of tensorstore dataarrays

ocf_data_sampler/load/gsp.py, ocf_data_sampler/numpy_sample/gsp.py, tests/load/test_load_gsp.py, tests/numpy_sample/test_gsp.py
This is two separate items
1. We don't use the nominal capacity anymore. That is a legacy thing and we proved using it was the wrong choice.
2.  Instead of using `isel()` we can index directly into the numpy array. This is faster
=> (Speed-up) Minimise GSP loading

ocf_data_sampler/utils.py
There was a bug in the `tensorstore_compute()` function introduced in #311. The intended behaviour was that we would start reading all the datasets to take advantage of tensorstore's async loading and then compute them all. Due to the recursion in that function we were actually reading and computing some of the datasets, then reading and computing others. This is inefficient. This PR corrects the behaviour
=> Bug recursion order

ocf_data_sampler/select/select_spatial_slice.py
Doing mins and maxes across the spatial coords is slow. In the load functions we make sure that the spatial coordinates are sorted in increasing order using [this function](https://github.com/openclimatefix/ocf-data-sampler/blob/main/ocf_data_sampler/load/utils.py#L15). We can make use of this to index the right values instead of doing mins and maxes
=> (Speed-up) Assume spatial coords are sorted

ocf_data_sampler/config/model.py, ocf_data_sampler/torch_datasets/datasets/pvnet_uk.py, ocf_data_sampler/torch_datasets/datasets/site.py, ocf_data_sampler/torch_datasets/utils/config_normalization_values_to_dicts.py
Change from using xarray DataArrays for the normalisation to numpy arrays
=> (Speed-up) Avoid xarray for normalisation constants

ocf_data_sampler/load/gsp.py
This PR changes the GSP data to be eagerly loaded instead of lazy. We've gone back and forth on this a couple of times, but I think eagerly loading is better. 
I tested this on donatello and got a 5% speed up in the dataloader when using 32 workers at a cost of an extra 8GB ram usage (32GB when lazy 40GB when eager). I think this cost os worth the speed-up. 
Another option could have been to use `xarray-tensorstore` for the GSP data, but at such a low RAM penalty I think eager loading is still better. It also removes uncertainty about what the best method for chunking the dataset is. And it allows the dataset to still be loaded from cloud storage anonymously by the open-data-pvnet community.
=> (Speed-up) Eagerly load GSP

ocf_data_sampler/torch_datasets/datasets/site.py
This adds casting the index in `_getitem_` as `int` because it is currently supplied as a tensor, which breaks pandas indexing. Judging by [this line](https://github.com/openclimatefix/ocf-data-sampler/blob/21e76fba7f2a64d6224d7a8be6443951d38e5aaa/ocf_data_sampler/torch_datasets/datasets/pvnet_uk.py#L272C9-L272C23) we've had the same issue in the GSP pipeline, so just adding this for site.
Running training on prem
=> Convert index to int for site getitem

ocf_data_sampler/load/site.py, tests/load/test_load_sites.py
Three changes are including in this PR:
- The main change is the relaxation of one of the checks to allow `NaN` values in the site generation data, this is due to the fact if you create a xarray dataset of generation data from different sites which have some non-overlapping time periods of data availability the resulting generation data variable will have `NaN` values which is fine as this is handled in our sampling logic [here](https://github.com/openclimatefix/ocf-data-sampler/blob/main/ocf_data_sampler/torch_datasets/datasets/site.py#L228-L231) which handles in each site separately and then combines all available samples
- The next biggest change is following suit from a change in the gsp loader to load the site generation data into memory rather than have this still be lazy loaded, …
=> Change site loader

ocf_data_sampler/torch_datasets/datasets/pvnet_uk.py, ocf_data_sampler/torch_datasets/datasets/site.py
openclimatefix/pvnet#458 allows us to remove the integer casting here
=> Remove cast index to int

tests/conftest.py
Relating to https://github.com/openclimatefix/ocf-data-sampler/issues/358
For tests/conftest.py only - few updates to just streamline:
- Use Path and constants - cleaner, consistent paths as opposed to os.path.
- Session RNG and related helpers - reproducible random data and less duplication in dataset creation pretty much.
- Consistent zarr writes and chunking - should be faster test runs, little simpler and no deprecated dtypes (must note, left this out as overall test time increased slightly?).
=> Conftest streamlining
