- ocf_data_sampler/numpy_batch/nwp.py
- ocf_data_sampler/select/select_spatial_slice.py
Two very small upgraders, that I found useful when running tests
Fixes #
CI tests
> small upgrades

- ocf_data_sampler/load/__init__..py
- ocf_data_sampler/load/__init__.py
fix file name from `__init__..py` to `__init__.py`
CI tests
> Rename __init__..py to __init__.py

- ocf_data_sampler/torch_datasets/pvnet_uk_regional.py
Add verbose for error for valid time periods, I needed something like this when working on pvnet_app
CI tests
> add check for valid time periods

- ocf_data_sampler/torch_datasets/pvnet_uk_regional.py
Remove the satellite standardisation since it is already normalised
> remove satellite scaling

- ocf_data_sampler/load/gsp.py
- ocf_data_sampler/load/nwp/providers/ecmwf.py
- ocf_data_sampler/load/nwp/providers/ukv.py
- ocf_data_sampler/load/satellite.py
- ocf_data_sampler/load/utils.py
Added a function to return a xr.DataArray from xr.Dataset when loading instead of hardcoding data variable name (e. g. as `return ds.ECMWF_UK`)
Ran the tests locally
> add function to return dataArray from Dataset

- README.md
> Adding traffic light badge

- ocf_data_sampler/numpy_batch/gsp.py
- ocf_data_sampler/torch_datasets/pvnet_uk_regional.py
- Add nan filling
- Make the target GSP location added to batch independent of adding the GSP data
- Eager-load the GSP data - not necessarily for production but I think we should have this in memory since its small enough
- Has been run with PVNet app
> Tweaks for production

- ocf_data_sampler/config/model.py
- ocf_data_sampler/constants.py
- ocf_data_sampler/numpy_batch/gsp.py
- ocf_data_sampler/numpy_batch/nwp.py
- ocf_data_sampler/numpy_batch/satellite.py
- ocf_data_sampler/numpy_batch/sun_position.py
- ocf_data_sampler/torch_datasets/pvnet_uk_regional.py
- pyproject.toml
- tests/numpy_batch/test_gsp.py
- tests/numpy_batch/test_nwp.py
- tests/numpy_batch/test_satellite.py
- tests/numpy_batch/test_sun_position.py
- tests/select/test_select_spatial_slice.py
- tests/torch_datasets/test_pvnet_uk_regional.py
remove ocf_datapipes
Fixes #58 
Ci tests
> Rm ocf datapipes

- ocf_data_sampler/numpy_batch/site.py
- tests/torch_datasets/test_site.py
Updated the attributes of SiteBatchKey but removing `site` prefix from some attributes.( Issue #79 )
> fix:removed site prefix from some attributes of SiteBatchkey class

- ocf_data_sampler/numpy_sample/collate.py
- tests/numpy_sample/test_collate.py
Renaming "sample" to "batch" for function which converts samples into a batch
> Update stack function name

- ocf_data_sampler/numpy_sample/gsp.py
- ocf_data_sampler/numpy_sample/nwp.py
- ocf_data_sampler/numpy_sample/satellite.py
- ocf_data_sampler/numpy_sample/site.py
Changed all the variables name `example` to `sample` in `numpy_samples` dir.
Fixes #123
> Changed example to sample in all numpy samples

- ocf_data_sampler/select/select_time_slice.py
- ocf_data_sampler/select/time_slice_for_dataset.py
Removes unused code and parameters from time slice selection functionality to improve code maintainability.
Fixes #107 
The changes focus on removing unused functionality while preserving core features validated by the test suite. This includes removing the unimplemented `_sel_fillinterp()` function and unused `max_steps_gap` parameter, while retaining the essential `fill_selection` parameter needed for handling out-of-bounds timestamps.
Simplifying the selection logic since we no longer need to handle interpolation.
The full test suite has been executed to verify that the removal of unused code does not impact existing functionality. Particular attention was paid to tests involving out-of-bounds timestamp handling to ensure the retained `fill_selection` parameter continues to function …
> Refactoring time slice selection

- ocf_data_sampler/numpy_sample/site.py
Add solar and datetime trig values to site sample when converting to numpy
> Add solar +date/times to site numpy

- README.md
- ocf_data_sampler/constants.py
- ocf_data_sampler/torch_datasets/README.md
Update readme for minor release
Ci tests
> Update README.md #minor

- ocf_data_sampler/torch_datasets/README.md
_Please delete the italicised instruction text!
Please include a summary of the change and which issue is fixed.
Please also include relevant motivation and context. List any dependencies that are required for this change._
Fixes #
_Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.
Please also list any relevant details for your test configuration_
_If your changes affect data processing, have you plotted any changes? i.e. have you done a quick sanity check?_
> remove site TODO from dataset README.md

- ocf_data_sampler/sample/uk_regional.py
Hot fix for `torch.load` with newer version of torch
Fixes #150
> force torch load

- ocf_data_sampler/config/__init__.py
- ocf_data_sampler/config/load.py
- ocf_data_sampler/config/model.py
- ocf_data_sampler/config/save.py
- ocf_data_sampler/load/__init__.py
- ocf_data_sampler/load/gsp.py
- ocf_data_sampler/load/load_dataset.py
- ocf_data_sampler/load/nwp/nwp.py
- ocf_data_sampler/load/nwp/providers/ecmwf.py
- ocf_data_sampler/load/nwp/providers/ukv.py
- ocf_data_sampler/load/nwp/providers/utils.py
- ocf_data_sampler/load/satellite.py
- ocf_data_sampler/load/site.py
- ocf_data_sampler/numpy_sample/collate.py
- ocf_data_sampler/numpy_sample/datetime_features.py
- ocf_data_sampler/select/find_contiguous_time_periods.py
- ocf_data_sampler/torch_datasets/datasets/pvnet_uk.py
- ocf_data_sampler/torch_datasets/datasets/site.py
- tests/config/test_config.py
- tests/config/test_load.py
- tests/config/test_save.py
- tests/load/test_load_sites.py
- tests/numpy_sample/test_datetime_features.py
- tests/torch_datasets/test_site.py
A crowd spring clean of some of the package
> Mob-programming clean up

- ocf_data_sampler/config/model.py
- ocf_data_sampler/constants.py
- ocf_data_sampler/select/fill_time_periods.py
- ocf_data_sampler/select/find_contiguous_time_periods.py
- ocf_data_sampler/select/geospatial.py
- ocf_data_sampler/select/location.py
- ocf_data_sampler/select/select_time_slice.py
- ocf_data_sampler/select/time_slice_for_dataset.py
- ocf_data_sampler/torch_datasets/datasets/pvnet_uk.py
- ocf_data_sampler/torch_datasets/datasets/site.py
- ocf_data_sampler/torch_datasets/utils/valid_time_periods.py
- tests/select/test_find_contiguous_time_periods.py
- tests/select/test_location.py
- tests/select/test_select_time_slice.py
- tests/test_sample/test_base.py
This PR merges the 3rd mob cleaning session
> Mob cleaning session 3

- pyproject.toml
See https://github.com/astral-sh/uv/issues/9513
> fix(pyproject): Workaround for setuptools complaints

- .github/workflows/branch_ci.yml
- .github/workflows/merged_ci.yml
- .github/workflows/pull_ci.yml
- .github/workflows/tagged_ci.yml
Adds a test matrix on multiple python versions for the unit test step. Seperates the external contribution test pipeline out into it's own workflow. Improves run names across workflows.
> fix(branch-ci): Run with test matrix, separate concerns

- ocf_data_sampler/load/load_dataset.py
- ocf_data_sampler/torch_datasets/datasets/pvnet_uk.py
- tests/torch_datasets/test_pvnet_uk.py
Pass through gsp_ids to `get_dataset_dict`
Fixes #230
> Pass gsp id through

- ocf_data_sampler/torch_datasets/sample/uk_regional.py
- ocf_data_sampler/torch_datasets/utils/validation_utils.py
- tests/torch_datasets/sample/test_uk_regional_sample.py
Added additional warning list alongside new validation - updated to utilise logging as opposed to list output
> Initial warnings added

- ocf_data_sampler/config/model.py
- ocf_data_sampler/load/load_dataset.py
- ocf_data_sampler/load/nwp/nwp.py
- ocf_data_sampler/load/nwp/providers/cloudcasting.py
- ocf_data_sampler/load/nwp/providers/ecmwf.py
- ocf_data_sampler/load/nwp/providers/gfs.py
- ocf_data_sampler/load/nwp/providers/icon.py
- ocf_data_sampler/load/nwp/providers/ukv.py
- ocf_data_sampler/load/nwp/providers/utils.py
- tests/conftest.py
- tests/load/test_load_nwp.py
- Add option to load NWP from public source
- refactored the nwp load, so nwp configruation is passed through instead
#228 
- CI tests
> add public and pass in nwp config to opening nwp

- ocf_data_sampler/load/gsp.py
- ocf_data_sampler/load/nwp/nwp.py
- ocf_data_sampler/load/nwp/providers/icon.py
- ocf_data_sampler/load/satellite.py
- ocf_data_sampler/load/site.py
- ocf_data_sampler/numpy_sample/nwp.py
- tests/conftest.py
- tests/load/test_load_gsp.py
- tests/load/test_load_nwp.py
- tests/load/test_load_satellite.py
- tests/load/test_load_sites.py
Relating directly to https://github.com/openclimatefix/ocf-data-sampler/issues/258
Type and value assertions added for the four load testing files
> Test load update

- ocf_data_sampler/load/nwp/nwp.py
Specific alterations:
- Removed a check for unknown provider
- Modified common_expected_dtypes - channel coordinate either np.str_ or np.object_ types
- Updated format in _validate_nwp_data to use actual_dtype.name
> nwp.py update

- ocf_data_sampler/torch_datasets/datasets/site.py
- tests/torch_datasets/test_site.py
Removed coarsen function and associated testing
> Remove coarsen function
